# Installation

In [10]:
#INSTALLATION

# Creating Array

In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print (arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# one's and zero's

In [6]:
a = np.ones((2,5), dtype=int)
print (a)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [23]:
zero = np.zeros((5,2), dtype = int)
print (zero)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


# Arange


In [12]:
range = np.arange(1,11,2)
print(range)

[1 3 5 7 9]


# Linespace

In [18]:
line_space = np.linspace(2,8,4,dtype = int)
print(line_space)

[2 4 6 8]


# Reshape

In [20]:
re_shape = arr_2d.reshape(4,2)
print(re_shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [22]:
x = np.arange(10,20).reshape(2,5)
print(x)

[[10 11 12 13 14]
 [15 16 17 18 19]]


# Ravel

In [25]:
x.ravel()
#n-D to 1 D 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])