# Installation

In [1]:
#INSTALLATION

# Creating Array

In [2]:
import numpy as np

In [3]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print (arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# one's and zero's

In [5]:
a = np.ones((2,5), dtype=int)
print (a)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [6]:
zero = np.zeros((5,2), dtype = int)
print (zero)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


# Arange


In [13]:
range = np.arange(1,11,2)
print(range)

[1 3 5 7 9]


# Linespace

In [7]:
line_space = np.linspace(2,8,4,dtype = int)
print(line_space)

[2 4 6 8]


# Reshape

In [8]:
re_shape = arr_2d.reshape(4,2)
print(re_shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [9]:
x = np.arange(10,20).reshape(2,5)
print(x)

[[10 11 12 13 14]
 [15 16 17 18 19]]


# Ravel

In [10]:
x.ravel()
#n-D to 1 D 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Transpose

In [15]:
x.transpose()
#name.T can also be used

array([[10, 15],
       [11, 16],
       [12, 17],
       [13, 18],
       [14, 19]])

# Mathematical operation

In [20]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(10,19).reshape(3,3)
sum=np.add(arr1,arr2)
sub=np.subtract(arr2,arr1)
print(arr1,arr2)
print(sum)
print(sub)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[10 11 12]
 [13 14 15]
 [16 17 18]]
[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [21]:
arr2/arr1

array([[10.        ,  5.5       ,  4.        ],
       [ 3.25      ,  2.8       ,  2.5       ],
       [ 2.28571429,  2.125     ,  2.        ]])

In [22]:
arr1 * arr2

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

# Matrix product

In [23]:
arr1 @ arr2

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [24]:
arr1.dot(arr2)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

# Maximum element

In [27]:
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [26]:
arr2.max()

18

In [30]:
arr2.max(axis = 0)
#max element in each colomn

array([16, 17, 18])

In [31]:
arr2.max(axis=1)
#max element in each row

array([12, 15, 18])

In [32]:
#similar for minimum use min

# Sum 

In [35]:
np.sum(arr2)
#or arr2.sum()

126

In [36]:
arr2.sum(axis=0)

array([39, 42, 45])

In [37]:
arr2.mean()

14.0

In [38]:
#similarly we can find log() exp() sqrt() std()-standarddeviation

# Array slicing

In [39]:
s = np.arange(1,101).reshape(10,10)
print (s)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [41]:
s[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
s[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [43]:
s[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [44]:
s[6:10 , 6:10]

array([[ 67,  68,  69,  70],
       [ 77,  78,  79,  80],
       [ 87,  88,  89,  90],
       [ 97,  98,  99, 100]])

# Array conctination and split

In [45]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [53]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [54]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [55]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [56]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [57]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
c=np.vstack((arr1,np.array([10,11,12])))
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [69]:
arr3=np.concatenate((c,c),axis=1)
print(arr3)

[[ 1  2  3  1  2  3]
 [ 4  5  6  4  5  6]
 [ 7  8  9  7  8  9]
 [10 11 12 10 11 12]]


In [71]:
np.split(arr3,2)

[array([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6]]),
 array([[ 7,  8,  9,  7,  8,  9],
        [10, 11, 12, 10, 11, 12]])]

In [72]:
np.split(arr3,2,axis=1)

[array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])]

In [73]:
#elements are in list form but the element of array is in .ndarray